### ISSUE TITLE
Negative file sizes

### ISSUE THREAD

**Issue by Send8213** [DyonR/magnetico2bitmagnet#2]
Problem:
Some torrents contain negative file sizes. These (rightfully) fail upon trying to import into Bitmagnet.

Proposed solution:
These torrents should be skipped when processing torrent files with torrent2*.

Context:
Bitmagnet's import doesn't gracefully handle these by skipping them.

**Comment by DyonR** [comment]
Just to make sure, are you using torrent2bitmaget or torrent2database?  
  
I've encountered this with 2 torrents out of 2 million torrents I've imported myself so far.  
I will take a closer look at _why_ this happens and see if it can be mitigated.  
Skipping them naturally sounds like a proper solution.

**Comment by DyonR** [comment]
Fixed in the latest commit

**Comment by DyonR** [comment]
Reopened, since I am not 100% satisfied with the fix.  
bitmagnet's WebUI refuses to load when a torrent has a negative integer in the results.

**Comment by Send8213** [comment]
Does the Bitmagnet UI only fail to load if you imported it directly into the database?

**Comment by Send8213** [comment]
Also, since a negative file size is invalid and isn't supported by any Bittorrent clients I've tested it with, shouldn't the default be to skip (maybe with some kind of warning or error count)?

**Comment by DyonR** [comment]
> Does the Bitmagnet UI only fail to load if you imported it directly into the database?

Yes. `/import` endpoint just gives an error.  
  
> Also, since a negative file size is invalid and isn't supported by any Bittorrent clients I've tested it with, shouldn't the default be to skip (maybe with some kind of warning or error count)?  
  
Something I am wondering is; what if the info_hash, the file name and everything else is fine, but just the 'length' (size) is just wrong/corrupt in the .torrent file. Maybe I am overthinking it, but just thinking out loud what could cause it. That's why in my recent commit I defaulted back to `0` instead of any negative integer.  

For `torrent2bitmagnet`, I could perhaps write an error.log file with any problematic torrents in it. I don't want to print it in the console/`stdout` directly, since doing that would lead into issues when piping into `curl`.
`torrent2database` could write it directly to console output, since that isn't used for piping.

**Comment by Send8213** [comment]
> Something I am wondering is; what if the info_hash, the file name and everything else is fine, but just the 'length' (size) is just wrong/corrupt in the .torrent file.

I think you might be overthinking it. If the torrent is corrupt in this way, then the infohash wouldn't be correct right? The problem files I've worked with so far have been named based on the hash and the hash your script has calculated matches the filename. A different, corrupted value for size (negative vs 'fixed' positive) would have had a different info hash and thus fixing it would actually make a new torrent with a different info hash that potentially no one has ever seen (and no one is seeding). I think it's therefore okay to just ignore these as corrupt/not following specs.

> For torrent2bitmagnet, I could perhaps write an error.log file with any problematic torrents in it. I don't want to print it in the console/stdout directly, since doing that would lead into issues when piping into curl.

Could you print the problems to stderr and just not redirect stderr when piping into curl?
